version: "3.9"

services:
  droneopssync:
    build: .
    container_name: droneopssync-server
    restart: unless-stopped
    ports:
      - "7474:7474"
    volumes:
      - "/volume1/docker/Log Sync/DroneLogData:/data/flightlogs"
    environment:
      - UPLOAD_DIR=/data/flightlogs
